#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Del_Scheduling_Tool")]
public partial class CourseDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDel_Course(Del_Course instance);
  partial void UpdateDel_Course(Del_Course instance);
  partial void DeleteDel_Course(Del_Course instance);
  #endregion
	
	public CourseDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Del_Scheduling_ToolConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public CourseDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CourseDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CourseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CourseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Del_Course> Del_Courses
	{
		get
		{
			return this.GetTable<Del_Course>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Del_Course")]
public partial class Del_Course : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CoursePK;
	
	private string _CourseStatus;
	
	private string _CourseName;
	
	private string _CourseCode;
	
	private System.Nullable<int> _Client_FK;
	
	private System.Nullable<int> _ActivityType_FK;
	
	private string _MasterInstructor;
	
	private string _CourseDescription;
	
	private System.Nullable<int> _CourseDuration;
	
	private System.Nullable<int> _MinClassSize;
	
	private System.Nullable<int> _MaxClassSize;
	
	private string _EquipmentNeeds;
	
	private System.Nullable<System.DateTime> _DateCreated;
	
	private System.Nullable<System.DateTime> _DateModified;
	
	private string _UpdatedBy;
	
	private string _CreatedBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCoursePKChanging(int value);
    partial void OnCoursePKChanged();
    partial void OnCourseStatusChanging(string value);
    partial void OnCourseStatusChanged();
    partial void OnCourseNameChanging(string value);
    partial void OnCourseNameChanged();
    partial void OnCourseCodeChanging(string value);
    partial void OnCourseCodeChanged();
    partial void OnClient_FKChanging(System.Nullable<int> value);
    partial void OnClient_FKChanged();
    partial void OnActivityType_FKChanging(System.Nullable<int> value);
    partial void OnActivityType_FKChanged();
    partial void OnMasterInstructorChanging(string value);
    partial void OnMasterInstructorChanged();
    partial void OnCourseDescriptionChanging(string value);
    partial void OnCourseDescriptionChanged();
    partial void OnCourseDurationChanging(System.Nullable<int> value);
    partial void OnCourseDurationChanged();
    partial void OnMinClassSizeChanging(System.Nullable<int> value);
    partial void OnMinClassSizeChanged();
    partial void OnMaxClassSizeChanging(System.Nullable<int> value);
    partial void OnMaxClassSizeChanged();
    partial void OnEquipmentNeedsChanging(string value);
    partial void OnEquipmentNeedsChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    #endregion
	
	public Del_Course()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoursePK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CoursePK
	{
		get
		{
			return this._CoursePK;
		}
		set
		{
			if ((this._CoursePK != value))
			{
				this.OnCoursePKChanging(value);
				this.SendPropertyChanging();
				this._CoursePK = value;
				this.SendPropertyChanged("CoursePK");
				this.OnCoursePKChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseStatus", DbType="VarChar(20)")]
	public string CourseStatus
	{
		get
		{
			return this._CourseStatus;
		}
		set
		{
			if ((this._CourseStatus != value))
			{
				this.OnCourseStatusChanging(value);
				this.SendPropertyChanging();
				this._CourseStatus = value;
				this.SendPropertyChanged("CourseStatus");
				this.OnCourseStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string CourseName
	{
		get
		{
			return this._CourseName;
		}
		set
		{
			if ((this._CourseName != value))
			{
				this.OnCourseNameChanging(value);
				this.SendPropertyChanging();
				this._CourseName = value;
				this.SendPropertyChanged("CourseName");
				this.OnCourseNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseCode", DbType="VarChar(255)")]
	public string CourseCode
	{
		get
		{
			return this._CourseCode;
		}
		set
		{
			if ((this._CourseCode != value))
			{
				this.OnCourseCodeChanging(value);
				this.SendPropertyChanging();
				this._CourseCode = value;
				this.SendPropertyChanged("CourseCode");
				this.OnCourseCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_FK", DbType="Int")]
	public System.Nullable<int> Client_FK
	{
		get
		{
			return this._Client_FK;
		}
		set
		{
			if ((this._Client_FK != value))
			{
				this.OnClient_FKChanging(value);
				this.SendPropertyChanging();
				this._Client_FK = value;
				this.SendPropertyChanged("Client_FK");
				this.OnClient_FKChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityType_FK", DbType="Int")]
	public System.Nullable<int> ActivityType_FK
	{
		get
		{
			return this._ActivityType_FK;
		}
		set
		{
			if ((this._ActivityType_FK != value))
			{
				this.OnActivityType_FKChanging(value);
				this.SendPropertyChanging();
				this._ActivityType_FK = value;
				this.SendPropertyChanged("ActivityType_FK");
				this.OnActivityType_FKChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterInstructor", DbType="VarChar(50)")]
	public string MasterInstructor
	{
		get
		{
			return this._MasterInstructor;
		}
		set
		{
			if ((this._MasterInstructor != value))
			{
				this.OnMasterInstructorChanging(value);
				this.SendPropertyChanging();
				this._MasterInstructor = value;
				this.SendPropertyChanged("MasterInstructor");
				this.OnMasterInstructorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseDescription", DbType="VarChar(200)")]
	public string CourseDescription
	{
		get
		{
			return this._CourseDescription;
		}
		set
		{
			if ((this._CourseDescription != value))
			{
				this.OnCourseDescriptionChanging(value);
				this.SendPropertyChanging();
				this._CourseDescription = value;
				this.SendPropertyChanged("CourseDescription");
				this.OnCourseDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseDuration", DbType="Int")]
	public System.Nullable<int> CourseDuration
	{
		get
		{
			return this._CourseDuration;
		}
		set
		{
			if ((this._CourseDuration != value))
			{
				this.OnCourseDurationChanging(value);
				this.SendPropertyChanging();
				this._CourseDuration = value;
				this.SendPropertyChanged("CourseDuration");
				this.OnCourseDurationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinClassSize", DbType="Int")]
	public System.Nullable<int> MinClassSize
	{
		get
		{
			return this._MinClassSize;
		}
		set
		{
			if ((this._MinClassSize != value))
			{
				this.OnMinClassSizeChanging(value);
				this.SendPropertyChanging();
				this._MinClassSize = value;
				this.SendPropertyChanged("MinClassSize");
				this.OnMinClassSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxClassSize", DbType="Int")]
	public System.Nullable<int> MaxClassSize
	{
		get
		{
			return this._MaxClassSize;
		}
		set
		{
			if ((this._MaxClassSize != value))
			{
				this.OnMaxClassSizeChanging(value);
				this.SendPropertyChanging();
				this._MaxClassSize = value;
				this.SendPropertyChanged("MaxClassSize");
				this.OnMaxClassSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentNeeds", DbType="VarChar(200)")]
	public string EquipmentNeeds
	{
		get
		{
			return this._EquipmentNeeds;
		}
		set
		{
			if ((this._EquipmentNeeds != value))
			{
				this.OnEquipmentNeedsChanging(value);
				this.SendPropertyChanging();
				this._EquipmentNeeds = value;
				this.SendPropertyChanged("EquipmentNeeds");
				this.OnEquipmentNeedsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateCreated
	{
		get
		{
			return this._DateCreated;
		}
		set
		{
			if ((this._DateCreated != value))
			{
				this.OnDateCreatedChanging(value);
				this.SendPropertyChanging();
				this._DateCreated = value;
				this.SendPropertyChanged("DateCreated");
				this.OnDateCreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateModified
	{
		get
		{
			return this._DateModified;
		}
		set
		{
			if ((this._DateModified != value))
			{
				this.OnDateModifiedChanging(value);
				this.SendPropertyChanging();
				this._DateModified = value;
				this.SendPropertyChanged("DateModified");
				this.OnDateModifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(50)")]
	public string UpdatedBy
	{
		get
		{
			return this._UpdatedBy;
		}
		set
		{
			if ((this._UpdatedBy != value))
			{
				this.OnUpdatedByChanging(value);
				this.SendPropertyChanging();
				this._UpdatedBy = value;
				this.SendPropertyChanged("UpdatedBy");
				this.OnUpdatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
