<?xml version="1.0" encoding="utf-8"?><Database Name="Del_Scheduling_Tool" Class="CourseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Del_Scheduling_Tool;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Del_Scheduling_ToolConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Del_Course" Member="Del_Courses">
    <Type Name="Del_Course">
      <Column Name="CoursePK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CourseCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Client_FK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivityType_FK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MasterInstructor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CourseDescription" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CourseDuration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinClassSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxClassSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EquipmentNeeds" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>