#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Del_Scheduling_Tool")]
public partial class SampleDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDel_User(Del_User instance);
  partial void UpdateDel_User(Del_User instance);
  partial void DeleteDel_User(Del_User instance);
  #endregion
	
	public SampleDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Del_Scheduling_ToolConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public SampleDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SampleDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SampleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SampleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Del_User> Del_Users
	{
		get
		{
			return this.GetTable<Del_User>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Del_User")]
public partial class Del_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UserPK;
	
	private string _EnterpriseID;
	
	private string _LastName;
	
	private string _FirstName;
	
	private string _ResourceStatus;
	
	private System.Nullable<int> _RoleType_FK;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserPKChanging(int value);
    partial void OnUserPKChanged();
    partial void OnEnterpriseIDChanging(string value);
    partial void OnEnterpriseIDChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnResourceStatusChanging(string value);
    partial void OnResourceStatusChanged();
    partial void OnRoleType_FKChanging(System.Nullable<int> value);
    partial void OnRoleType_FKChanged();
    #endregion
	
	public Del_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UserPK
	{
		get
		{
			return this._UserPK;
		}
		set
		{
			if ((this._UserPK != value))
			{
				this.OnUserPKChanging(value);
				this.SendPropertyChanging();
				this._UserPK = value;
				this.SendPropertyChanged("UserPK");
				this.OnUserPKChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterpriseID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string EnterpriseID
	{
		get
		{
			return this._EnterpriseID;
		}
		set
		{
			if ((this._EnterpriseID != value))
			{
				this.OnEnterpriseIDChanging(value);
				this.SendPropertyChanging();
				this._EnterpriseID = value;
				this.SendPropertyChanged("EnterpriseID");
				this.OnEnterpriseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceStatus", DbType="VarChar(20)")]
	public string ResourceStatus
	{
		get
		{
			return this._ResourceStatus;
		}
		set
		{
			if ((this._ResourceStatus != value))
			{
				this.OnResourceStatusChanging(value);
				this.SendPropertyChanging();
				this._ResourceStatus = value;
				this.SendPropertyChanged("ResourceStatus");
				this.OnResourceStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleType_FK", DbType="Int")]
	public System.Nullable<int> RoleType_FK
	{
		get
		{
			return this._RoleType_FK;
		}
		set
		{
			if ((this._RoleType_FK != value))
			{
				this.OnRoleType_FKChanging(value);
				this.SendPropertyChanging();
				this._RoleType_FK = value;
				this.SendPropertyChanged("RoleType_FK");
				this.OnRoleType_FKChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
