<?xml version="1.0" encoding="utf-8"?><Database Name="Del_Scheduling_Tool" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Del_Scheduling_Tool;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Del_Scheduling_ToolConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Del_User" Member="Del_Users">
    <Type Name="Del_User">
      <Column Name="UserPK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnterpriseID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ResourceStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RoleType_FK" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>